package com.milo.ms.domain;

public enum BeerOrderStatusEnum {
    NEW, VALIDATED, VALIDATE_PENDING, VALIDATION_EXCEPTION,
    ALLOCATED_PENDING, ALLOCATED, ALLOCATION_EXCEPTION,
    PENDING_INVENTORY, PICKED_UP, DELIVERED, DELIVERY_EXCEPTION
}
